Covid_19_Bangladesh-main/App_Login/urls.py
from django.urls import path
from App_Login import views
app_name='App_Login'
urlpatterns=[
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/',views.logout_user, name='logout'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('change_profile/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add_picture/', views.add_pro_pic, name='add_pro_pic'),
    path('change_picture/', views.change_pro_pic, name='change_pro_pic'), 
]

Covid_19_Bangladesh-main/Covid_19_BD/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('account/', include('App_Login.urls')),
    path('covid/',include('App_Covid.urls')),
    path('map/', include('Map_Data.urls')),#new
    path('dash/',include('Dashboard.urls')),
    path('more/', include('More_Info.urls')),
    path('',views.Index, name='Index'),#kew jdi just site er nam likhe tahole eta execute hbe
    #path('dash/',include('DashBoard.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Covid_19_Bangladesh-main/Map_Data/urls.py
from django.urls import path
from Map_Data import views
from django.conf.urls import url
app_name='Map_Data'

urlpatterns=[
    path('show_map/', views.index, name='show_map'),
    url('selectCountry',views.drillDownACountry,name='drillDown'),
]

Covid_19_Bangladesh-main/App_Login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user=models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic=models.ImageField(upload_to='profile_pics')

Covid_19_Bangladesh-main/App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from App_Login.models import UserProfile

class SignUpForm(UserCreationForm):
    email=forms.EmailField(label="Email Address", required=True)
    class Meta:
        model=User
        fields=('first_name','last_name', 'username', 'email', 'password1', 'password2')

class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')

class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic',)

Covid_19_Bangladesh-main/App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from App_Login.forms import SignUpForm, UserProfileChange, ProfilePic
# Create your views here.
def sign_up(request):
    form=SignUpForm()
    registered=False
    if request.method=='POST':
        form=SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered=True
    dict={'form': form, 'registered': registered}
    return render(request, 'App_Login/signup.html', context=dict)

def login_page(request):
    form=AuthenticationForm()
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('Index'))
    return render(request, 'App_Login/login.html', context={'form':form})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('Index'))
@login_required
def user_profile(request):
    return render(request, 'App_Login/user_profile.html', context={})

@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)#request.POST er value gulo dea instance er value replace korlm
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)#16:00 again load korlm notun info gulo, na hoe puraton info gulai dekhabe
    return render(request, 'App_Login/change_profile.html', context={'form':form})

@login_required
def pass_change(request):
    current_user = request.user
    current_
    print("Current_User is: -", current_user)
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'App_Login/pass_change.html', context={'form':form, 'changed':changed})

@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:user_profile'))
    return render(request, 'App_Login/pro_pic_add.html', context={'form':form})

@login_required
def change_pro_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:user_profile'))
    return render(request, 'App_Login/pro_pic_add.html', context={'form':form})

Covid_19_Bangladesh-main/templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block  body_block %}
<form method="POST">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-warning btn-sm">Change</button>
</form>
{% endblock %}

Covid_19_Bangladesh-main/templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
<h2>User Login</h2>
<form method="POST">
{{form|crispy}}
{% csrf_token %}
<button type="submit" class="btn btn-primary btn-sm">Login</button>
</form>
{% endblock %}

Covid_19_Bangladesh-main/templates/App_Login/pass_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
{% if changed %}
<div class="alert alert-success">
  Password Change Successfully!
</div>
{% endif %}
<form method="POST">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-warning btn-sm">Change</button>
</form>
{% endblock %}

Covid_19_Bangladesh-main/templates/App_Login/pro_pic_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
<h2>Add Your Profile Picture:</h2>
<form method="POST" enctype="multipart/form-data">
  {{form|crispy}}
  {% csrf_token %}
  <button type="submit" class="btn btn-success btn-sm">Add</button>
</form>
{% endblock %}

Covid_19_Bangladesh-main/templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
{% if registered %}
<div class="alert alert-success">
  Account Created Successfully!<a href="{% url 'App_Login:login' %}">Login Here</a>
</div>

{% else %}
<h2>Create New Account(User)</h2>
<form  method="post">
  {{form|crispy}}
  {% csrf_token %}
  <button type="submit" class="btn btn-success btn-sm"> Create Account</button>
</form>
<br>
<p>Already have an account? <a href="{% url 'App_Login:login' %}">Login Here</a></p>
{% endif %}
{% endblock %}

Covid_19_Bangladesh-main/templates/App_Login/user_profile.html
{% extends 'base.html'%}
{%block body_block%}
<h2>Your Profile: </h2>


<!--<table border="4">
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Name</th>
  </tr>

  <tr>
    <td>{{user.username}}</td>
    <td>{{user.email}}</td>
    <td>{{user.first_name}} {{user.last_name}}</td>
  </tr>
</table>-->
{% if user.user_profile %}
<img src="/media/{{user.user_profile.profile_pic}}" class="rounded-circle" width="100px">
<a href="{% url 'App_Login:change_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
{% else %}

<img src="/media/profile_pics/general.png" class="rounded-circle" width="100px">
<a href="{% url 'App_Login:add_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
{% endif %}
<br>
<br>
<b>Username: </b><p>{{user.username}}</p>
<b>Email: </b><p>{{user.email}}</p>
<b>Name: </b><p>{{user.first_name}} {{user.last_name}}</p>
<br>
<a href="{%url 'App_Login:user_change'%}" class="btn btn-warning btn-sm">Change Profile Info</a>

{% endblock %}