Covid_19_Bangladesh-main/App_Covid/urls.py
from django.urls import path
from App_Covid import views

app_name='App_Covid'

urlpatterns=[
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>/', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
]

Covid_19_Bangladesh-main/App_Login/urls.py
from django.urls import path
from App_Login import views
app_name='App_Login'
urlpatterns=[
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/',views.logout_user, name='logout'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('change_profile/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add_picture/', views.add_pro_pic, name='add_pro_pic'),
    path('change_picture/', views.change_pro_pic, name='change_pro_pic'), 
]

Covid_19_Bangladesh-main/Covid_19_BD/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('account/', include('App_Login.urls')),
    path('covid/',include('App_Covid.urls')),
    path('map/', include('Map_Data.urls')),#new
    path('dash/',include('Dashboard.urls')),
    path('more/', include('More_Info.urls')),
    path('',views.Index, name='Index'),#kew jdi just site er nam likhe tahole eta execute hbe
    #path('dash/',include('DashBoard.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Covid_19_Bangladesh-main/Dashboard/urls.py
from django.urls import path
from Dashboard import views
from django.conf.urls import url
app_name='Dashboard'

urlpatterns=[
    path('show_dash/', views.index, name='show_dash'),
]

Covid_19_Bangladesh-main/Map_Data/urls.py
from django.urls import path
from Map_Data import views
from django.conf.urls import url
app_name='Map_Data'

urlpatterns=[
    path('show_map/', views.index, name='show_map'),
    url('selectCountry',views.drillDownACountry,name='drillDown'),
]

Covid_19_Bangladesh-main/More_Info/urls.py
from django.urls import path
from More_Info import views
from django.conf.urls import url
app_name='More_Info'

urlpatterns=[
    path('show_more/', views.home, name='show_more'),
]

Covid_19_Bangladesh-main/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">


  <!--=========================DashBoard=================-->

  <title>{% block title_block %} Blogs {% endblock %}</title>

  <!--=========================== first index============================-->

  <!-- ======================== first index=================== -->
  <!--=====Dash====-->

<style>
  .display-8 {
    font-weight: 300;
    font-size: 35px;
  }

  .display-7 {
    font-weight: 600;
    font-size: 60px;
  }

  .color1 {
    background-color: #7175B6;
    color: white;
  }

  .color2 {
    background-color: #FF3E4D;
    color: white;
  }

  .color3 {
    background-color: #FD0101;
    color: white;
  }

  .color4 {
    background-color: #2ecc72;
    color: white;
  }

  .color5 {
    background-color: #31E522;
    color: white;
  }

  .number {
    font-weight: 300;
    font-size: 40px;
    float: right;
  }
</style>

  <!--===Dash===-->




</head>

<body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-blue">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'Index' %}"><b><img src="/media/cvd.png" class="rounded-circle" width="50px"></b></a>

        <!--main url er vitor index name ta ase tai index er age kisu dite hbe na-->
        Mujahid Jui Sajib Mridula Zahid
      </li>

      {%if user.is_authenticated %}
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          {{user.username}}
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{%url 'App_Covid:create_blog' %}"><b>Share Your Thoughts</b></a>
          <a class="dropdown-item" href="{%url 'App_Covid:my_blogs' %}"><b>My Blogs</a>
          <a class="dropdown-item" href="{%url 'App_Login:user_profile' %}"><b>My Profile</b></a>
          <hr>
          <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
        </div>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'Dashboard:show_dash' %}"><b>Bangladesh Info</b></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'Map_Data:show_map' %}"><b>Map_Visualization</b></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=""><b>More_Info</b></a>
        </li>
      </div>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{%url 'App_Login:signup' %}"><b>SignUp</b></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'App_Login:login' %}"><b>LogIn</b></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'admin:index' %}"><b>Admin</b></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'Dashboard:show_dash' %}"><b>Bangladesh Info</b></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'Map_Data:show_map' %}"><b>Map_Visualization</b></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'More_Info:show_more' %}"><b>More Info</b></a>
      </li>

      {% endif %}
    </ul>

  </nav>
  <div class="container" style="padding-top:20px">
    {% block body_block %}
    {% endblock %}
    <!-- First Index -->

    <!-- First Index -->
  </div>

</body>


</html>

Covid_19_Bangladesh-main/templates/dash.html
{% extends 'base.html' %}


<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  <style>
    .display-8 {
      font-weight: 300;
      font-size: 35px;
    }

    .color1 {
      background-color: #2475B0;
      color: white;
    }

    .color2 {
      background-color: #FF3E4D;
      color: white;
    }

    .color3 {
      background-color: #B83227;
      color: white;
    }

    .color4 {
      background-color: #2ecc72;
      color: white;
    }

    .color5 {
      background-color: #26ae60;
      color: white;
    }
  </style>
  <style>
    .display-8 {
      font-weight: 300;
      font-size: 35px;
    }

    .display-7 {
      font-weight: 600;
      font-size: 60px;
    }

    .color1 {
      background-color: #7175B6;
      color: white;
    }

    .color2 {
      background-color: #FF3E4D;
      color: white;
    }

    .color3 {
      background-color: #FD0101;
      color: white;
    }

    .color4 {
      background-color: #2ecc72;
      color: white;
    }

    .color5 {
      background-color: #31E522;
      color: white;
    }

    .number {
      font-weight: 300;
      font-size: 40px;
      float: right;
    }
  </style>

</head>
{% block body_block %}
<body class="p-3">

  <br>
  <h4 class="border rounded p-3">
    <div class="display-7">
      <h1>Covid 19 - Bangladesh Data</h1>
    </div>
  </h4>
  <hr>
  <div class="container-fluid">
    <div class="row">
      <div class="card col m-2 color1">
        <div class="card-body">
          <h4 class="card-title">New Confirmed</h4>
          <p class="card-text number">{{globalSummary.NewConfirmed}}</p>
        </div>
      </div>
      <div class="card col m-2 color2">
        <div class="card-body">
          <h4 class="card-title">NewDeaths</h4>
          <p class="card-text number">{{globalSummary.NewDeaths}}</p>
        </div>
      </div>
      <div class="card col m-2 color3">
        <div class="card-body">
          <h4 class="card-title">Total Deaths</h4>
          <p class="card-text number">{{globalSummary.TotalDeaths}}</p>
        </div>
      </div>
      <div class="card col m-2 color4">
        <div class="card-body">
          <h4 class="card-title">New Recovered</h4>
          <p class="card-text number">{{globalSummary.NewRecovered}}</p>
        </div>
      </div>
      <div class="card col m-2 color5">
        <div class="card-body">
          <h4 class="card-title">Total Recovered</h4>
          <p class="card-text number">{{globalSummary.TotalRecovered}}</p>
        </div>
      </div>

    </div>
    <hr>

    <h4 class="border rounded p-3">
      <div class="display-8">
        <h1>District Wise Summary</h1>
      </div>
    </h4>
    <table class="table">
      <thead>
        <tr>
          <th>Sno.</th>
          <th>District</th>
          <th>Total Confirmed</th>
          <th>Total Deaths</th>
          <th>Total Recovered</th>
        </tr>
      </thead>
      <tbody>
                {% for c in all %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{c.0}}</td>
                    <td>{{c.1.TotalConfirmed}}</td>
                    <td>{{c.1.TotalDeaths}}</td>
                    <td>{{c.1.TotalRecovered}}</td>
                </tr>
                {% endfor %}

            </tbody>
    </table>

  </div>
  </div>
  </div>

{% endblock %}

Covid_19_Bangladesh-main/templates/index.html
<html>

    <meta charset="utf-8">

    <!-- Load d3.js -->
    <script src="https://d3js.org/d3.v4.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="https://code.highcharts.com/maps/highmaps.js"></script>
    <script src="https://code.highcharts.com/maps/modules/data.js"></script>
    <script src="https://code.highcharts.com/maps/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/maps/modules/offline-exporting.js"></script>
    <script src="https://code.highcharts.com/mapdata/custom/world.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>

    <!-- Flag sprites service provided by Martijn Lafeber, https://github.com/lafeber/world-flags-sprite/blob/master/LICENSE -->
    <link rel="stylesheet" type="text/css" href="//github.com/downloads/lafeber/world-flags-sprite/flags32.css" />


    <style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li {
  float: left;
}

li a, .dropbtn {
  display: inline-block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover, .dropdown:hover .dropbtn {
  background-color: red;
}

li.dropdown {
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {background-color: #f1f1f1;}

.dropdown:hover .dropdown-content {
  display: block;
}
</style>
    </head>

  <body>
<ul>
<li><a href="{%url 'Index' %}"><b><img src="/media/cvd.png" class="rounded-circle" width="50px"></b></a></li>
<li><a href="#news">News</a></li>
<li class="dropdown">
  <a href="javascript:void(0)" class="dropbtn">Dropdown</a>
  <div class="dropdown-content">
    <a href="#">Link 1</a>
    <a href="#">Link 2</a>
    <a href="#">Link 3</a>
  </div>
</li>
</ul>
        <div>
            <div class="col-lg-3" style="float: left;  max-height: 650px;max-width:400px;overflow: scroll; overflow-x:hidden;">
                <div style="background-color: rgb(41, 41, 40);">

                    <span style="color: rgb(255, 255, 255); text-align: center;"><h2>Total Infected: {{overallCount}}</h2></span>
                </div>
                <div class="col-lg-12">
                    <form method="post" enctype="multipart/form-data" action="selectCountry">
                    {% csrf_token %}
                    <div class="col-lg-4" style="float: left;">
                        {% for con in contryNames %}
                        <table style="border-width: 2px; border: #333;">
                        <tr>
                            <input type="submit" value={{con}} name="countryName" style="width:100px;">
                        </tr>
                    </table>
                        {% endfor %}
                    </div>
                    <div style="float: left;">
                        <canvas id="myChart" style="height: 6650px; width: 280px;"></canvas>
                    </div>
                    </form>


                </div>
            </div>
            <div class="col-lg-6" style="float: left;">
                <br>
                <br>
                <div id="mapChart" style="height: 650px; width: 800px;"></div>
            </div>
            <div class="col-lg-3" style="float: left;max-width: 300px;  max-height: 650px;overflow: scroll; overflow-x:hidden;">
                <div style="background-color: rgb(41, 41, 40);">

                    <span style="color: rgb(255, 255, 255); text-align: center;"><h2>Last 5 days Counts</h2></span>
                </div>
                <div class="col-lg-12">
                        <div id="heatchart"></div>
                </div>
            </div>
            <!-- <div  style="float: left;  max-height: 650px;max-width:400px;overflow: scroll; overflow-x:hidden;">
                <br>
                <div id="heatchart"></div>
            </div>   -->
            </div>

        </div>
        <br>

        <div style="height: 300px;">
            <canvas id="lineChart" style="height: 400px;"></canvas>
        </div>


    </body>

<script>

    var ctx = document.getElementById('myChart').getContext('2d');
    var chartOptions = {
                            legend: {
                                display: false
                                    },
                            scales: {
                                xAxes: [{
                                    barPercentage:1
                                    }],
                                yAxes: [
                                        // {barPercentage: 1},
                                        // {gridLines:{drawBorder: false}},
                                        {ticks: {display:false}},
                                        // {ticks: {mirror: true}},
                                        {display: false},

                                        ],
                            elements: {
                                rectangle: {
                                borderSkipped: 'left',
                                }
                            }
                            }
                        };
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'horizontalBar',

        // The data for our dataset
        data: {
            labels: {{ contryNames|safe }},
            datasets: [{
                data: {{ countsVal|safe }},
                label: 'Infected Counts',
                barThickness:'flex',
                backgroundColor:'#03a9fc',

            }]
        },



        // Configuration options go here
        options: chartOptions
});
</script>

<script>
    var data2={{datasetForLine|safe}};
    var chartOptions2 = {
            legend: {
                display: false
                    }
        };
    var ctx2 = document.getElementById('lineChart').getContext('2d');
	var myLineChart = new Chart(ctx2, {
    type: 'line',
    data: {labels:{{axisvalues|safe}},
            datasets:data2,},
    options: chartOptions2
});
</script>
<script>

var someDataMap=[{'code3': 'AFG', 'name': 'Afghanistan', 'value': 484, 'code': 'AF'},
 {'code3': 'ALB', 'name': 'Albania', 'value': 409, 'code': 'AL'},
 {'code3': 'DZA', 'name': 'Algeria', 'value': 1666, 'code': 'DZ'},
 {'code3': 'AND', 'name': 'Andorra', 'value': 583, 'code': 'AD'},
 {'code3': 'AGO', 'name': 'Angola', 'value': 19, 'code': 'AO'}];

 var someData2=[{
		"code3": "ABW",
		"name": "Aruba",
		"value": 582.34,
		"code": "AW"
	},
	{
		"code3": "AFG",
		"name": "Afghanistan",
		"value": 53.08,
		"code": "AF"
	},
	{
		"code3": "AGO",
		"name": "Angola",
		"value": 23.11,
		"code": "AO"
    }];
 var someData3={{dataForMapGraph|safe}};
    Highcharts.getJSON('https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/world-population-density.json', function (data) {

// Prevent logarithmic errors in color calulcation
data.forEach(function (p) {
    p.value = (p.value < 1 ? 1 : p.value);
});

// Initiate the chart
Highcharts.mapChart('mapChart', {

    chart: {
        map: 'custom/world'
    },

    title: {
        text: 'World Map COVID-19 Infection '
    },

    legend: {
        title: {
            text: 'Infected Population',
            style: {
                color: ( // theme
                    Highcharts.defaultOptions &&
                    Highcharts.defaultOptions.legend &&
                    Highcharts.defaultOptions.legend.title &&
                    Highcharts.defaultOptions.legend.title.style &&
                    Highcharts.defaultOptions.legend.title.style.color
                ) || 'black'
            }
        }
    },

    mapNavigation: {
        enabled: true,
        buttonOptions: {
            verticalAlign: 'bottom'
        }
    },

    tooltip: {
        backgroundColor: 'none',
        borderWidth: 0,
        shadow: false,
        useHTML: true,
        padding: 0,
        pointFormat: '<span class="f32"><span class="flag {point.properties.hc-key}">' +
            '</span></span> {point.name}<br>' +'<span><h4>{point.value}</h4></span>',
        positioner: function () {
            return { x: 0, y: 250 };
        }
    },

    colorAxis: {
        min: 1,
        max: {{maxVal|safe}},
        type: 'logarithmic'
    },

    series: [{
        data: someData3,
        joinBy: ['iso-a3', 'code3'],
        name: 'Infected Counts',
        states: {
            hover: {
                color: '#a4edba'
            }
        }
    }]
});
});

</script>

<script>
var options = {
          series: {{dataForheatMap|safe}},
          chart: {
          height: 6500,
          type: 'heatmap',
        },
        dataLabels: {
          enabled: true
        },
        dataLabels: {
            position: 'top'
            },
        colors: ["#008FFB"],
        yaxis: {
      show: false},
      xaxis: {
          type: 'category',
          categories: {{dateCat|safe}}
        },

        };
var chart4 = new ApexCharts(document.querySelector("#heatchart"), options);

chart4.render();
</script>
</html>

Covid_19_Bangladesh-main/templates/index2.html
<html>

    <meta charset="utf-8">

    <!-- Load d3.js -->
    <script src="https://d3js.org/d3.v4.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="https://code.highcharts.com/maps/highmaps.js"></script>
    <script src="https://code.highcharts.com/maps/modules/data.js"></script>
    <script src="https://code.highcharts.com/maps/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/maps/modules/offline-exporting.js"></script>
    <script src="https://code.highcharts.com/mapdata/custom/world.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>

    <!-- Flag sprites service provided by Martijn Lafeber, https://github.com/lafeber/world-flags-sprite/blob/master/LICENSE -->
    <link rel="stylesheet" type="text/css" href="//github.com/downloads/lafeber/world-flags-sprite/flags32.css" />


    <style>
        /* Add some padding on document's body to prevent the content
        to go underneath the header and footer */
        body{
            padding-top: 60px;
            padding-bottom: 40px;
        }
        .fixed-header, .fixed-footer{
            width: 100%;
            position: fixed;
            background: #333;
            padding: 10px 0;
            color: #fff;
        }
        .fixed-header{
            top: 0;
        }
        .fixed-footer{
            bottom: 0;
        }
        .container{
            width: 80%;
            margin: 0 auto; /* Center the DIV horizontally */
        }
        nav a{
            color: #fff;
            text-decoration: none;
            padding: 7px 25px;
            display: inline-block;
        }
    </style>
    </head>
    <body>
        <div class="fixed-header">
            <div class>
                <nav>
                    <a href="/"><span style="font-size: 40px;">COVID-19 DashBoard</span></a>

                </nav>
            </div>
        </div>
        <div>
            <div class="col-lg-3" style="float: left;  max-height: 650px;max-width:400px;overflow: scroll; overflow-x:hidden;">
                <div style="background-color: rgb(41, 41, 40);">

                    <span style="color: rgb(255, 255, 255); text-align: center;"><h2>Total Infected: {{overallCount}}</h2></span>
                </div>
                <div class="col-lg-12">
                    <form method="post" enctype="multipart/form-data" action="selectCountry">
                    {% csrf_token %}
                    <div class="col-lg-4" style="float: left;">
                        {% for con in contryNames %}
                        <table style="border-width: 2px; border: #333;">
                        <tr>
                            <input type="submit" value={{con}} name="countryName" style="width:100px;">
                        </tr>
                    </table>
                        {% endfor %}
                    </div>
                    <div style="float: left;">
                        <canvas id="myChart" style="height: 6650px; width: 280px;"></canvas>
                    </div>
                    </form>


                </div>
            </div>
            <div class="col-lg-6" style="float: left;">
                <br>
                <br>
                <h2 style="text-align: center;">Analysis on {{countryName}}</h2><br>
                    <canvas id="lineChart" style="height: 450px;"></canvas>
            </div>
            <div class="col-lg-3" style="float: left;max-width: 300px;  max-height: 650px;overflow: scroll; overflow-x:hidden;">

            </div>
            </div>

        </div>
        <br>


    </body>

<script>

    var ctx = document.getElementById('myChart').getContext('2d');
    var chartOptions = {
                            legend: {
                                display: false
                                    },
                            scales: {
                                xAxes: [{
                                    barPercentage:1
                                    }],
                                yAxes: [
                                        // {barPercentage: 1},
                                        // {gridLines:{drawBorder: false}},
                                        {ticks: {display:false}},
                                        // {ticks: {mirror: true}},
                                        {display: false},

                                        ],
                            elements: {
                                rectangle: {
                                borderSkipped: 'left',
                                }
                            }
                            }
                        };
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'horizontalBar',

        // The data for our dataset
        data: {
            labels: {{ contryNames|safe }},
            datasets: [{
                data: {{ countsVal|safe }},
                label: 'Infected Counts',
                barThickness:'flex',
                backgroundColor:'#03a9fc',

            }]
        },



        // Configuration options go here
        options: chartOptions
});
</script>

<script>
    var data2={{datasetsForLine|safe}};
    var chartOptions2 = {
            legend: {
                display: true
                    },
                    scales: {
						yAxes: [{
							type: 'linear', // only linear but allow scale type registration. This allows extensions to exist solely for log scale for instance
							display: true,
							position: 'left',
							id: 'y-axis-1',
						}, {
							type: 'linear', // only linear but allow scale type registration. This allows extensions to exist solely for log scale for instance
							display: true,
							position: 'right',
							id: 'y-axis-2',

							// grid line settings
							gridLines: {
								drawOnChartArea: false, // only want the grid lines for one axis to show up
							},
						}],
					},
        };
    var ctx2 = document.getElementById('lineChart').getContext('2d');
	var myLineChart = new Chart(ctx2, {
        type: 'line',
        data: {labels:{{axisvalues|safe}},datasets:data2,},
        options: chartOptions2
        });
</script>

</html>

Covid_19_Bangladesh-main/templates/more.html
{% extends 'base.html' %}
<head>
    <title>welcome to this world</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
{% block body_block %}
<body>
    <div class="jumbotron">
        <center><h1>More Information About Covid-19 in Bangladesh</h1>
           <a href="/" class="btn btn-danger">Refresh News</a>
        </form>
    </center>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-3">
                    <h2 class="text-centre" style="color:rgb(0, 204, 102);">প্রথম আলো</h2>
                    {% for n in toi_news %}
                    <h7> -  {{n}} </h7>
                    <hr>
                    {% endfor %}
                    <br>
            </div>
            <div class="col-3">
                    <h2 class="text-centre" style="color:Tomato;">বাংলা ২৪ লাইভ নিউজপেপার</h2>
                    {% for htn in ht_news %}
                    <h7> - {{htn}} </h7>
                    <hr>
                    {% endfor %}
                    <br>
            </div>
            <div class="col-3">
                    <h2 class="text-centre" style="color: rgb(0, 0, 255);">ডেইলি ইত্তেফাক</h2>
                    {% for htn in third_news %}
                    <h7> - {{htn}} </h7>
                    <hr>
                    {% endfor %}
                    <br>
            </div>
            <div class="col-3">
                    <b><h2 class="text-centre" style="color: rgb(0, 102, 153);">যুগান্তর</h2></b>
                    {% for htn in fourth_news %}
                    <h7> - {{htn}} </h7>
                    <hr>
                    {% endfor %}
                    <br>
            </div>
        </div>


</div>
    <script
src="http://code.jquery.com/jquery-3.3.1.min.js"
integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock %}